### PR TITLE
Create Login Page for Spring Boot Application

### PR DESCRIPTION
**Pull request by Duaa3**

### CODE REVIEW

**Review by RoqayaAlmamari — APPROVED** [review]
👍

**Comment by Duaa3** [comment]
[Create Login Page for Spring Boot Application](https://trello.com/c/dknlj0Ec/176-create-login-page-for-spring-boot-application)

**Review by FatemaAlbalushi — APPROVED** [review]
Good job

**Review by BaraahAlKalbani — APPROVED** [review]
👍🏻 Excellent Work

**Pull request merged**
